export const REQUEST_MOVIE_DETAILS = 'REQUEST_MOVIE_DETAILS';
export const RECEIVE_MOVIE_DETAILS = 'RECEIVE_MOVIE_DETAILS';
export const RECEIVE_MOVIE_DETAILS_SUCCESS = 'RECEIVE_MOVIE_DETAILS_SUCCESS';
